#!/bin/sh
#
# Generates array of textfile-paths contained in ssh-logs directory.
#
# @author (c)2017 Kim Olsen <kim@pizslacker.org>
#
# @lastchange 20130320-12:43-GMT+1

DIALOG=$(which dialog)

if [ -x "$DIALOG" ]; then
    # Temporary loglist.
    LIST_TMP="/tmp/sshlog-list.tmp";
    SEL_TMP="/tmp/sshlog-list-sel.tmp";
    # SSH-LOGS directory.
    SSHLOGS="ssh-logs"
    # Log-directory.
    LOGDIR="$HOME/$SSHLOGS";
    # List-array from log-directory.
    LOGLIST=$(ls "$LOGDIR");
    # Option-counter.
    CNT=1;
    # For each '$ITEM' in '$LOGLIST', do, done loop.
    for ITEM in $LOGLIST
    do
        echo "$CNT $ITEM " >> "$LIST_TMP";
        CNT=$(( $CNT + 1 ));
    done
    # Runs 'dialog' with menu-selection.
    dialog --title "sshlog-list (v1.5)" --menu \
    "Choose which log you want to view:" 32 48 25 $(cat "$LIST_TMP") 2> "$SEL_TMP";
    rm -f "$LIST_TMP" 2>&1 > /dev/null;
    # Re-set 'CNT', and loop to select correct logfile for viewing.
    CNT=1;
    for ITEM in $LOGLIST
    do
        if [ $(cat "$SEL_TMP") = "$CNT" ]; then
            {
            sshlog-viewer "$SSHLOGS"/"$ITEM";
            }
        fi
        CNT=$(( $CNT + 1 ));
    done
    `which clear`;
    rm -f "$SEL_TMP" 2>&1 > /dev/null;
else
    $(which clear);
    echo;
    echo " You need to install \033[1;37mdialog\033[0m to use \033[1;37msshlog-list\033[0m (a GUI-like menu front-end).";
    echo;
    echo -n " Press \033[1;37m[Enter]\033[0m to quit. " && read QUIT;
    if [ "$QUIT" != NULL ]; then
        {
        $(which clear);
        exit 1;
        }
    fi
fi
